version: '3'

services:
  reviews:
    build: .
    depends_on:
      - 'database'
    ports: 
      - '3003:3003'

  database:
    build: ./database
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'reviewsDB'
      NYSQL_USER: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    
